num1 =eval(input("Enter your first number:")) 
num2 =eval(input("Enter your second number:")) 
print("The sum of" ,num1,"and" ,num2,"is", num1 + num2 ) 
print("The difference of" ,num1,"and" ,num2,"is", num1 - num2 ) 
print("The product of" ,num1,"and" ,num2,"is", num1 * num2 ) 
print("The qoutient of" ,num1,"and" ,num2,"is", num1 / num2 ) 
print(num1,"exponent","by",num2,"is", num1 ** num2) 
print("The remainder of" ,num1,"and" ,num2,"is", num1 // num2 ) 
print("The floor division of" ,num1,"and" ,num2,"is", num1 % num2 )